# Generated by Django 6.0.7 on 2026-07-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villes', to='api.region')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emetteur', models.CharField(choices=[('POUR_MOI', 'Signaler pour vous'), ('POUR_QUELQUUN', "Signaler pour quelqu'un")], max_length=30, verbose_name='Émetteur')),
                ('genre', models.CharField(blank=True, choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('AUTRE', 'Autre'), ('NON_PRECISE', 'Non précisé')], max_length=30, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('cyberharcelement_type', models.CharField(max_length=255, verbose_name='Type de cyberviolence')),
                ('type_contenu', models.CharField(max_length=255, verbose_name='Type de contenu')),
                ('plateforme', models.CharField(max_length=255)),
                ('url', models.TextField(verbose_name='Lien vers le contenu')),
                ('capture_image_url', models.TextField(blank=True, null=True, verbose_name='Capture image')),
                ('accompagnement_demande', models.BooleanField(default=False, verbose_name='Accompagnement demandé')),
                ('type_accompagnement', models.CharField(blank=True, choices=[('JURIDIQUE', 'Juridique'), ('PSYCHIQUE', 'Psychique')], max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='NOUVEAU', max_length=30)),
                ('raison', models.TextField(blank=True, null=True, verbose_name='Raison / commentaire interne')),
                ('langue', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='api.ville')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
