# Generated by Django 6.0.7 on 2026-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_ANALYSE', 'En analyse'), ('EN_APPROBATION', 'En approbation'), ('APPROUVE', 'Approuvé'), ('TRANSMIS_PARTENAIRE', 'Transmis au partenaire'), ('TRAITE', 'Traité'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé')], default='NOUVEAU', max_length=30),
        ),
    ]
