# Generated by Django 6.0.7 on 2026-08-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_signalement_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.signalement')),
            ],
        ),
    ]
