# Generated by Django 6.0.7 on 2026-08-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historiquesignalement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='age',
            field=models.CharField(blank=True, choices=[('5_12', 'Âges de 5 à 12 ans'), ('13_17', 'Âges de 13 à 17 ans'), ('18_25', 'Âges de 18 à 25 ans'), ('PLUS_26', 'Plus de 26 ans')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='cyberharcelement_type',
            field=models.CharField(choices=[('PROPOS_HAINE', 'Propos de haine'), ('PROPOS_RACISTE', 'Propos raciste ou discriminatoire'), ('DIFFAMATION', 'Diffamation'), ('USURPATION_IDENTITE', "Usurpation d'identité"), ('PHOTOS_INTIMES', 'Publication de photos intimes ou personnelles'), ('VIDEOS_INTIMES', 'Publication de vidéos intimes ou personnelles'), ('MENACE_PHOTOS_INTIMES', 'Menace de publier des photos intimes ou personnelles'), ('MENACE_VIDEOS_INTIMES', 'Menace de publier des vidéos intimes ou personnelles'), ('AUTRES', 'Autres')], max_length=50, verbose_name='Type de cyberviolence'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='genre',
            field=models.CharField(blank=True, choices=[('FEMME', 'Femme'), ('HOMME', 'Homme')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='plateforme',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('MESSENGER', 'Messenger'), ('TIKTOK', 'Tiktok')], max_length=30),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_contenu',
            field=models.CharField(choices=[('VIDEO', 'Vidéo'), ('IMAGE', 'Image'), ('COMMENTAIRE', 'Commentaire'), ('COMPTE', 'Compte'), ('AUTRES', 'Autres')], max_length=30, verbose_name='Type de contenu'),
        ),
    ]
