# Generated by Django 6.0.7 on 2026-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_signalement_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='capture_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='captures/'),
        ),
    ]
