# Generated by Django 6.0.7 on 2026-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_signalement_capture_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='partenaire',
            field=models.CharField(blank=True, choices=[('IBNIES', 'IBNIES'), ('ONDES', 'ONDES'), ('ATECS', 'ATECS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='cyberharcelement_type',
            field=models.CharField(choices=[('PROPOS_HAINE', 'Propos de haine'), ('PROPOS_RACISTE_DISCRIMINATOIRE', 'Propos raciste ou discriminatoire'), ('DIFFAMATION', 'Diffamation'), ('USURPATION_IDENTITE', "Usurpation d'identité"), ('PHOTOS_INTIMES', 'Publication de photos intimes ou personnelles'), ('VIDEOS_INTIMES', 'Publication de vidéos intimes ou personnelles'), ('MENACE_PHOTOS_INTIMES', 'Menace de publier des photos intimes ou personnelles'), ('MENACE_VIDEOS_INTIMES', 'Menace de publier des vidéos intimes ou personnelles'), ('AUTRES', 'Autres')], max_length=50, verbose_name='Type de cyberviolence'),
        ),
    ]
